# Basic numeric benchmark

In [4]:
import numpy as np
import timeit

In [5]:
def do_stuff1(x): return [(i*2)**2 for i in x]
def do_stuff1_numpy(x): return (x*2)**2
def do_stuff2(x): return  [i*2 if i < 1_000 else i*3 for i in x]
def do_stuff2_numpy(x): return x*2*(x < 1_000) + x*3*(x >= 1_000)

In [6]:
do_stuff1(range(100_000));

In [7]:
%%timeit
for x in range(100):
    do_stuff1(range(10_000+x))

234 ms ± 2.56 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%%timeit
for x in range(100):
    do_stuff1_numpy(np.arange(100_000+x))

15.7 ms ± 726 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
%%timeit
for x in range(100):
    do_stuff2(range(10_000+x))

72.2 ms ± 840 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%%timeit
for x in range(100):
    do_stuff2_numpy(np.arange(100_000+x))

56.5 ms ± 739 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
np.arange(100_000).dtype

dtype('int32')

# AD in Tensorflow

In [99]:
import tensorflow as tf
import numpy as np

In [119]:
c = np.array([[1.], [2.]])

In [120]:
Q = np.array([[2., 3.], [4., 5.]])

In [121]:
x = tf.Variable([[2.],[1.]])

In [122]:
def loss(x): 
    return np.array(0.5)*\
    tf.transpose(x) @ Q @ x + c.T @ x

In [123]:
loss(x).numpy()

array([[17.5]], dtype=float32)

In [124]:
with tf.GradientTape() as tape:
    y = loss(x)
tape.gradient(y, x).numpy()

array([[ 8.5],
       [14. ]], dtype=float32)

# AD in PyTorch

In [112]:
import torch

In [113]:
x = torch.tensor([[2.],[1.]], requires_grad=True)

In [114]:
c = torch.tensor([[1.], [2.]])

In [115]:
Q = torch.tensor([[2., 3.], [4., 5.]])

In [116]:
loss = 0.5*x.T @ Q @ x + c.T @ x
loss

tensor([[17.5000]], grad_fn=<AddBackward0>)

In [117]:
loss.backward()

In [118]:
x.grad

tensor([[ 8.5000],
        [14.0000]])